/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 12.2.0-14 -fPIC -O3) */

module tenbaset_rx(clk_i, rst_i, rx_dat_i, rx_active_i, mii_rx_ena_o, mii_rx_clk_o, mii_rx_dat_o);
  wire _00_;
  wire [31:0] _01_;
  wire [1:0] _02_;
  wire [6:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [6:0] _06_;
  wire [4:0] _07_;
  wire [3:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [4:0] _13_;
  wire [4:0] _14_;
  wire _15_;
  wire [6:0] _16_;
  wire [4:0] _17_;
  wire [6:0] _18_;
  wire [4:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [1:0] _24_;
  wire [4:0] _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire [4:0] _31_;
  wire _32_;
  wire _33_;
  wire [1:0] _34_;
  wire [1:0] _35_;
  wire [3:0] _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire [3:0] _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire [31:0] _44_;
  wire [1:0] _45_;
  wire _46_;
  wire [1:0] _47_;
  wire [4:0] _48_;
  wire [1:0] _49_;
  wire _50_;
  wire _51_;
  wire [3:0] _52_;
  wire [3:0] _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  reg [30:0] _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  input clk_i;
  wire clk_i;
  output mii_rx_clk_o;
  wire mii_rx_clk_o;
  output [3:0] mii_rx_dat_o;
  wire [3:0] mii_rx_dat_o;
  output mii_rx_ena_o;
  wire mii_rx_ena_o;
  wire [30:0] r;
  wire [30:0] rin;
  input rst_i;
  wire rst_i;
  input rx_active_i;
  wire rx_active_i;
  input rx_dat_i;
  wire rx_dat_i;
  assign _16_ = _15_ ? 7'h03 : { _06_[4:0], r[1:0] };
  assign _17_ = r[26:22] + 5'h01;
  assign _18_ = _09_ ? _16_ : { _06_[4:0], r[1:0] };
  assign _19_ = _09_ ? _14_ : _17_;
  assign _20_ = rx_active_i & rx_dat_i;
  assign _21_ = _20_ & r[10];
  assign _23_ = _21_ & r[11];
  assign _24_ = _23_ ? 2'h1 : _18_[1:0];
  assign _25_ = _23_ ? _18_[6:2] : 5'h06;
  assign _26_ = _23_ ? 1'h0 : 1'h1;
  assign _27_ = _23_ ? _07_[0] : 1'h0;
  assign _28_ = _23_ ? _08_[3] : 1'h0;
  assign _29_ = r[1:0] == 2'h0;
  assign _30_ = { 30'h00000000, r[8:7] } == 32'd3;
  assign _31_ = _30_ ? 5'h15 : r[21:17];
  assign _32_ = r[29] & r[30];
  assign _34_ = _32_ ? 2'h2 : _18_[1:0];
  assign _35_ = _32_ ? 2'h0 : _06_[6:5];
  assign _36_ = _32_ ? 4'hd : _31_[3:0];
  assign _37_ = r[1:0] == 2'h1;
  assign _38_ = { 30'h00000000, r[8:7] } == 32'd3;
  assign _39_ = _08_[1] & _38_;
  assign _00_ = rx_active_i | r[10];
  assign _40_ = _39_ ? _07_[4:1] : r[20:17];
  assign _41_ = r[1:0] == 2'h2;
  assign _42_ = rx_active_i | r[10];
  assign _43_ = ~ _42_;
  assign _11_ = rx_dat_i & _00_;
  assign _45_ = _43_ ? 2'h0 : _18_[1:0];
  assign _46_ = r[1:0] == 2'h3;
  function [1:0] \188 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \188  = b[1:0];
      4'b??1?:
        \188  = b[3:2];
      4'b?1??:
        \188  = b[5:4];
      4'b1???:
        \188  = b[7:6];
      default:
        \188  = a;
    endcase
  endfunction
  assign _47_ = \188 (2'hx, { _45_, _18_[1:0], _34_, _24_ }, { _46_, _41_, _37_, _29_ });
  function [4:0] \191 ;
    input [4:0] a;
    input [19:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \191  = b[4:0];
      4'b??1?:
        \191  = b[9:5];
      4'b?1??:
        \191  = b[14:10];
      4'b1???:
        \191  = b[19:15];
      default:
        \191  = a;
    endcase
  endfunction
  assign _48_ = \191 (5'hxx, { _18_[6:2], _18_[6:2], _18_[6:2], _25_ }, { _46_, _41_, _37_, _29_ });
  function [1:0] \193 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \193  = b[1:0];
      4'b??1?:
        \193  = b[3:2];
      4'b?1??:
        \193  = b[5:4];
      4'b1???:
        \193  = b[7:6];
      default:
        \193  = a;
    endcase
  endfunction
  assign _49_ = \193 (2'hx, { _06_[6:5], _06_[6:5], _35_, 2'h0 }, { _46_, _41_, _37_, _29_ });
  function [0:0] \195 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \195  = b[0:0];
      4'b??1?:
        \195  = b[1:1];
      4'b?1??:
        \195  = b[2:2];
      4'b1???:
        \195  = b[3:3];
      default:
        \195  = a;
    endcase
  endfunction
  assign _50_ = \195 (1'hx, { 1'h1, r[9], r[9], _26_ }, { _46_, _41_, _37_, _29_ });
  function [0:0] \198 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \198  = b[0:0];
      4'b??1?:
        \198  = b[1:1];
      4'b?1??:
        \198  = b[2:2];
      4'b1???:
        \198  = b[3:3];
      default:
        \198  = a;
    endcase
  endfunction
  assign _51_ = \198 (1'hx, { _07_[0], _07_[0], _07_[0], _27_ }, { _46_, _41_, _37_, _29_ });
  function [3:0] \201 ;
    input [3:0] a;
    input [15:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \201  = b[3:0];
      4'b??1?:
        \201  = b[7:4];
      4'b?1??:
        \201  = b[11:8];
      4'b1???:
        \201  = b[15:12];
      default:
        \201  = a;
    endcase
  endfunction
  assign _52_ = \201 (4'hx, { _07_[4:1], _07_[4:1], _07_[4:1], 4'h0 }, { _46_, _41_, _37_, _29_ });
  function [3:0] \204 ;
    input [3:0] a;
    input [15:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \204  = b[3:0];
      4'b??1?:
        \204  = b[7:4];
      4'b?1??:
        \204  = b[11:8];
      4'b1???:
        \204  = b[15:12];
      default:
        \204  = a;
    endcase
  endfunction
  assign _53_ = \204 (4'hx, { r[20:17], _40_, _36_, r[20:17] }, { _46_, _41_, _37_, _29_ });
  function [0:0] \207 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \207  = b[0:0];
      4'b??1?:
        \207  = b[1:1];
      4'b?1??:
        \207  = b[2:2];
      4'b1???:
        \207  = b[3:3];
      default:
        \207  = a;
    endcase
  endfunction
  assign _54_ = \207 (1'hx, { r[21], r[21], _31_[4], 1'h0 }, { _46_, _41_, _37_, _29_ });
  function [0:0] \210 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \210  = b[0:0];
      4'b??1?:
        \210  = b[1:1];
      4'b?1??:
        \210  = b[2:2];
      4'b1???:
        \210  = b[3:3];
      default:
        \210  = a;
    endcase
  endfunction
  assign _56_ = \210 (1'hx, { _08_[3], _08_[3], _08_[3], _28_ }, { _46_, _41_, _37_, _29_ });
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) _57_ <= 31'h00000200;
    else _57_ <= rin;
  assign _22_ = ~ r[9];
  assign _33_ = _22_ | rx_active_i;
  assign _44_ = { 27'h0000000, r[6:2] } + 32'd1;
  assign _55_ = r[11] != r[12];
  assign _58_ = $signed({ 27'h0000000, r[6:2] }) >= $signed(32'd6);
  assign _59_ = _58_ & _55_;
  assign _60_ = { 30'h00000000, r[8:7] } == 32'd3;
  assign _01_ = { 30'h00000000, r[8:7] } + 32'd1;
  assign _02_ = _60_ ? 2'h0 : _01_[1:0];
  assign _03_ = _59_ ? { _02_, 5'h00 } : { r[8:7], _44_[4:0] };
  assign _04_ = _59_ ? { r[11], r[16:14] } : r[16:13];
  assign _05_ = _59_ ? { r[29], r[11], 2'h2 } : { r[30:29], 1'h0, r[27] };
  assign _06_ = _33_ ? _03_ : r[8:2];
  assign _07_ = _33_ ? { _04_, r[11] } : r[16:12];
  assign _08_ = _33_ ? _05_ : { r[30:29], 1'h0, r[27] };
  assign _09_ = ~ r[9];
  assign _10_ = { 30'h00000000, r[8:7] } == 32'd0;
  assign _12_ = { 30'h00000000, r[8:7] } == 32'd2;
  assign _13_ = _12_ ? 5'h00 : r[26:22];
  assign _14_ = _10_ ? 5'h1f : _13_;
  assign _15_ = $signed({ 27'h0000000, r[6:2] }) >= $signed(32'd18);
  assign r = _57_;
  assign rin = { _56_, _08_[2:0], _19_, _54_, _53_, _52_, _51_, _11_, rx_active_i, _50_, _49_, _48_, _47_ };
  assign mii_rx_ena_o = r[21];
  assign mii_rx_clk_o = r[26];
  assign mii_rx_dat_o = r[20:17];
endmodule
