/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 12.2.0-14 -fPIC -O3) */

module tenbaset_tx(clk_i, rst_i, mii_tx_ena_i, mii_tx_dat_i, mii_tx_clk_o, tx_dac_n_o, tx_dac_p_o);
  wire [2:0] _000_;
  wire [2:0] _001_;
  wire [2:0] _002_;
  wire [2:0] _003_;
  wire [2:0] _004_;
  wire [2:0] _005_;
  wire [2:0] _006_;
  wire [2:0] _007_;
  wire [2:0] _008_;
  wire [2:0] _009_;
  wire [2:0] _010_;
  wire [2:0] _011_;
  wire [2:0] _012_;
  wire [2:0] _013_;
  wire [2:0] _014_;
  wire _015_;
  wire [2:0] _016_;
  wire [2:0] _017_;
  wire [2:0] _018_;
  wire [2:0] _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire [2:0] _022_;
  wire [2:0] _023_;
  wire [2:0] _024_;
  wire [2:0] _025_;
  wire [2:0] _026_;
  wire [2:0] _027_;
  wire [2:0] _028_;
  wire [2:0] _029_;
  wire [2:0] _030_;
  wire [2:0] _031_;
  wire _032_;
  wire [2:0] _033_;
  wire [4:0] _034_;
  wire [1:0] _035_;
  wire [31:0] _036_;
  wire [5:0] _037_;
  wire [6:0] _038_;
  wire [33:0] _039_;
  wire [12:0] _040_;
  wire _041_;
  wire _042_;
  wire [31:0] _043_;
  wire [1:0] _044_;
  wire [31:0] _045_;
  wire [31:0] _046_;
  wire [5:0] _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire [33:0] _052_;
  wire [3:0] _053_;
  wire _054_;
  wire [3:0] _055_;
  wire _056_;
  wire [33:0] _057_;
  wire [5:0] _058_;
  wire [2:0] _059_;
  wire [2:0] _060_;
  wire [2:0] _061_;
  wire _062_;
  wire [2:0] _063_;
  wire [2:0] _064_;
  wire [2:0] _065_;
  wire _066_;
  wire _067_;
  wire [2:0] _068_;
  wire [2:0] _069_;
  wire [2:0] _070_;
  wire _071_;
  wire [2:0] _072_;
  wire [2:0] _073_;
  wire [2:0] _074_;
  wire [2:0] _075_;
  wire [2:0] _076_;
  wire [31:0] _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [31:0] _081_;
  wire [1:0] _082_;
  wire [31:0] _083_;
  wire [5:0] _084_;
  wire _085_;
  wire [1:0] _086_;
  wire [31:0] _087_;
  wire [31:0] _088_;
  wire _089_;
  wire [2:0] _090_;
  wire [2:0] _091_;
  wire _092_;
  wire [5:0] _093_;
  reg [83:0] _094_;
  wire _095_;
  wire [2:0] _096_;
  wire [2:0] _097_;
  wire [2:0] _098_;
  wire [2:0] _099_;
  wire _100_;
  wire [2:0] _101_;
  wire [2:0] _102_;
  wire [2:0] _103_;
  wire [2:0] _104_;
  wire [2:0] _105_;
  wire [2:0] _106_;
  wire [2:0] _107_;
  wire [2:0] _108_;
  wire [2:0] _109_;
  wire [2:0] _110_;
  wire [33:0] _111_;
  wire [2:0] _112_;
  wire [2:0] _113_;
  wire [2:0] _114_;
  wire [2:0] _115_;
  wire [2:0] _116_;
  wire [2:0] _117_;
  wire [2:0] _118_;
  wire [2:0] _119_;
  wire [2:0] _120_;
  wire [2:0] _121_;
  wire [5:0] _122_;
  input clk_i;
  wire clk_i;
  output mii_tx_clk_o;
  wire mii_tx_clk_o;
  input [3:0] mii_tx_dat_i;
  wire [3:0] mii_tx_dat_i;
  input mii_tx_ena_i;
  wire mii_tx_ena_i;
  wire [83:0] r;
  wire [83:0] rin;
  input rst_i;
  wire rst_i;
  output [2:0] tx_dac_n_o;
  wire [2:0] tx_dac_n_o;
  output [2:0] tx_dac_p_o;
  wire [2:0] tx_dac_p_o;
  assign _000_ = _059_[0] ? 3'h6 : 3'h4;
  assign _001_ = _060_[0] ? 3'h0 : 3'h1;
  assign _002_ = _060_[0] ? 3'h6 : 3'h4;
  assign _003_ = _063_[0] ? 3'h7 : 3'h6;
  assign _004_ = _063_[0] ? 3'h2 : 3'h3;
  assign _005_ = _064_[0] ? 3'h7 : 3'h6;
  assign _006_ = _064_[0] ? 3'h2 : 3'h3;
  assign _007_ = _068_[0] ? 3'h7 : 3'h6;
  assign _008_ = _068_[0] ? 3'h2 : 3'h3;
  assign _009_ = _070_[0] ? 3'h7 : 3'h6;
  assign _010_ = _070_[0] ? 3'h2 : 3'h3;
  assign _011_ = _072_[0] ? 3'h0 : 3'h1;
  assign _012_ = _072_[0] ? 3'h6 : 3'h4;
  assign _013_ = _074_[0] ? 3'h0 : 3'h1;
  assign _014_ = _074_[0] ? 3'h6 : 3'h4;
  assign _015_ = _034_[3] ? _055_[1] : _055_[0];
  assign _016_ = _059_[0] ? 3'h0 : 3'h1;
  assign _017_ = _059_[0] ? 3'h4 : 3'h7;
  assign _018_ = _060_[0] ? 3'h3 : 3'h1;
  assign _019_ = _060_[0] ? 3'h4 : 3'h7;
  assign _020_ = _063_[0] ? 3'h4 : 3'h5;
  assign _021_ = _063_[0] ? 3'h1 : 3'h1;
  assign _022_ = _064_[0] ? 3'h4 : 3'h5;
  assign _023_ = _064_[0] ? 3'h1 : 3'h1;
  assign _024_ = _068_[0] ? 3'h4 : 3'h5;
  assign _025_ = _068_[0] ? 3'h1 : 3'h1;
  assign _026_ = _070_[0] ? 3'h4 : 3'h5;
  assign _027_ = _070_[0] ? 3'h1 : 3'h1;
  assign _028_ = _072_[0] ? 3'h3 : 3'h1;
  assign _029_ = _072_[0] ? 3'h4 : 3'h7;
  assign _030_ = _074_[0] ? 3'h3 : 3'h1;
  assign _031_ = _074_[0] ? 3'h4 : 3'h7;
  assign _032_ = _034_[3] ? _055_[3] : _055_[2];
  assign _033_ = _059_[0] ? 3'h3 : 3'h1;
  assign _097_ = _059_[1] ? _017_ : _000_;
  assign _099_ = _060_[1] ? _018_ : _001_;
  assign _101_ = _060_[1] ? _019_ : _002_;
  assign _103_ = _063_[1] ? _020_ : _003_;
  assign _104_ = _063_[1] ? _021_ : _004_;
  assign _106_ = _064_[1] ? _022_ : _005_;
  assign _107_ = _064_[1] ? _023_ : _006_;
  assign _109_ = _068_[1] ? _024_ : _007_;
  assign _110_ = _068_[1] ? _025_ : _008_;
  assign _113_ = _070_[1] ? _026_ : _009_;
  assign _114_ = _070_[1] ? _027_ : _010_;
  assign _116_ = _072_[1] ? _028_ : _011_;
  assign _117_ = _072_[1] ? _029_ : _012_;
  assign _119_ = _074_[1] ? _030_ : _013_;
  assign _120_ = _074_[1] ? _031_ : _014_;
  assign _095_ = _034_[4] ? _032_ : _015_;
  assign _096_ = _059_[1] ? _033_ : _016_;
  assign _044_ = _042_ ? r[1:0] : 2'h0;
  assign _046_ = _042_ ? _043_ : 32'd0;
  assign _047_ = _042_ ? 6'h31 : 6'h3f;
  assign _048_ = r[1:0] == 2'h1;
  assign _049_ = r[81:79] == 3'h7;
  assign _050_ = r[83:79] == 5'h1f;
  assign _051_ = ~ mii_tx_ena_i;
  assign _052_ = _054_ ? 34'h000000003 : r[33:0];
  assign _053_ = _051_ ? r[78:75] : mii_tx_dat_i;
  assign _054_ = _051_ & _050_;
  assign _055_ = _050_ ? _053_ : r[78:75];
  assign _057_ = _049_ ? _052_ : r[33:0];
  assign _058_ = _049_ ? { _055_, _095_, r[74] } : r[78:73];
  assign _059_ = 3'h7 - r[81:79];
  assign _060_ = 3'h7 - r[81:79];
  assign _061_ = ~ _102_;
  assign _062_ = { r[73], r[74] } == 2'h0;
  assign _063_ = 3'h7 - r[81:79];
  assign _034_ = r[83:79] + 5'h01;
  assign _064_ = 3'h7 - r[81:79];
  assign _065_ = ~ _108_;
  assign _066_ = { r[73], r[74] } == 2'h1;
  assign _068_ = 3'h7 - r[81:79];
  assign _069_ = ~ _112_;
  assign _070_ = 3'h7 - r[81:79];
  assign _071_ = { r[73], r[74] } == 2'h2;
  assign _072_ = 3'h7 - r[81:79];
  assign _073_ = ~ _118_;
  assign _074_ = 3'h7 - r[81:79];
  function [2:0] \211 ;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \211  = b[2:0];
      3'b?1?:
        \211  = b[5:3];
      3'b1??:
        \211  = b[8:6];
      default:
        \211  = a;
    endcase
  endfunction
  assign _075_ = \211 (_121_, { _115_, _065_, _061_ }, { _071_, _066_, _062_ });
  function [2:0] \212 ;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \212  = b[2:0];
      3'b?1?:
        \212  = b[5:3];
      3'b1??:
        \212  = b[8:6];
      default:
        \212  = a;
    endcase
  endfunction
  assign _076_ = \212 (_073_, { _069_, _105_, _098_ }, { _071_, _066_, _062_ });
  assign _077_ = r[65:34] + 32'd1;
  assign _079_ = r[1:0] == 2'h2;
  assign _080_ = $signed(r[33:2]) < $signed(32'd24);
  assign _081_ = r[33:2] + 32'd1;
  assign _082_ = _080_ ? r[1:0] : 2'h0;
  assign _083_ = _080_ ? _081_ : 32'd0;
  assign _084_ = _080_ ? 6'h31 : 6'h3f;
  assign _085_ = r[1:0] == 2'h3;
  function [1:0] \248 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \248  = b[1:0];
      4'b??1?:
        \248  = b[3:2];
      4'b?1??:
        \248  = b[5:4];
      4'b1???:
        \248  = b[7:6];
      default:
        \248  = a;
    endcase
  endfunction
  assign _086_ = \248 (2'hx, { _082_, _057_[1:0], _044_, _039_[1:0] }, { _085_, _079_, _048_, _041_ });
  function [31:0] \252 ;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \252  = b[31:0];
      4'b??1?:
        \252  = b[63:32];
      4'b?1??:
        \252  = b[95:64];
      4'b1???:
        \252  = b[127:96];
      default:
        \252  = a;
    endcase
  endfunction
  assign _087_ = \252 (32'hxxxxxxxx, { _083_, _057_[33:2], _046_, _039_[33:2] }, { _085_, _079_, _048_, _041_ });
  function [31:0] \255 ;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \255  = b[31:0];
      4'b??1?:
        \255  = b[63:32];
      4'b?1??:
        \255  = b[95:64];
      4'b1???:
        \255  = b[127:96];
      default:
        \255  = a;
    endcase
  endfunction
  assign _088_ = \255 (32'hxxxxxxxx, { r[65:34], _077_, r[65:34], r[65:34] }, { _085_, _079_, _048_, _041_ });
  function [2:0] \260 ;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \260  = b[2:0];
      4'b??1?:
        \260  = b[5:3];
      4'b?1??:
        \260  = b[8:6];
      4'b1???:
        \260  = b[11:9];
      default:
        \260  = a;
    endcase
  endfunction
  assign _090_ = \260 (3'hx, { _084_[2:0], _075_, _047_[2:0], _040_[2:0] }, { _085_, _079_, _048_, _041_ });
  function [2:0] \265 ;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \265  = b[2:0];
      4'b??1?:
        \265  = b[5:3];
      4'b?1??:
        \265  = b[8:6];
      4'b1???:
        \265  = b[11:9];
      default:
        \265  = a;
    endcase
  endfunction
  assign _091_ = \265 (3'hx, { _084_[5:3], _076_, _047_[5:3], _040_[5:3] }, { _085_, _079_, _048_, _041_ });
  function [0:0] \269 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \269  = b[0:0];
      4'b??1?:
        \269  = b[1:1];
      4'b?1??:
        \269  = b[2:2];
      4'b1???:
        \269  = b[3:3];
      default:
        \269  = a;
    endcase
  endfunction
  assign _092_ = \269 (1'hx, { r[72], r[72], r[72], _040_[6] }, { _085_, _079_, _048_, _041_ });
  function [5:0] \273 ;
    input [5:0] a;
    input [23:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \273  = b[5:0];
      4'b??1?:
        \273  = b[11:6];
      4'b?1??:
        \273  = b[17:12];
      4'b1???:
        \273  = b[23:18];
      default:
        \273  = a;
    endcase
  endfunction
  assign _093_ = \273 (6'hxx, { r[78:73], _058_, r[78:73], _040_[12:7] }, { _085_, _079_, _048_, _041_ });
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) _094_ <= 84'h000fc0000000000000000;
    else _094_ <= rin;
  assign _098_ = _059_[2] ? _097_ : _096_;
  assign _045_ = r[33:2] + 32'd1;
  assign _102_ = _060_[2] ? _101_ : _099_;
  assign _105_ = _063_[2] ? _104_ : _103_;
  assign _056_ = r[83:79] == 5'h1f;
  assign _108_ = _064_[2] ? _107_ : _106_;
  assign _067_ = mii_tx_ena_i & _056_;
  assign _112_ = _068_[2] ? _110_ : _109_;
  assign _115_ = _070_[2] ? _114_ : _113_;
  assign _078_ = _067_ ? 1'h1 : r[72];
  assign _118_ = _072_[2] ? _117_ : _116_;
  assign _121_ = _074_[2] ? _120_ : _119_;
  assign _089_ = r[83:79] == 5'h04;
  assign _100_ = $signed(r[33:2]) > $signed(32'd1280000);
  assign _111_ = _100_ ? 34'h000000001 : { _045_, r[1:0] };
  assign _122_ = _100_ ? 6'h38 : 6'h3f;
  assign _035_ = r[72] ? 2'h2 : _111_[1:0];
  assign _036_ = r[72] ? _045_ : _111_[33:2];
  assign _037_ = r[72] ? 6'h3f : _122_;
  assign _038_ = r[72] ? { mii_tx_dat_i, mii_tx_dat_i[0], 2'h0 } : { r[78:73], _078_ };
  assign _039_ = _089_ ? { _036_, _035_ } : { _045_, r[1:0] };
  assign _040_ = _089_ ? { _038_, _037_ } : { r[78:73], _078_, 6'h3f };
  assign _041_ = r[1:0] == 2'h0;
  assign _042_ = $signed(r[33:2]) < $signed(32'd8);
  assign _043_ = r[33:2] + 32'd1;
  assign r = _094_;
  assign rin = { _034_, _093_, _092_, _091_, _090_, _088_, _087_, _086_ };
  assign mii_tx_clk_o = r[83];
  assign tx_dac_n_o = r[68:66];
  assign tx_dac_p_o = r[71:69];
endmodule
